name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: false
  NX_BRANCH: ${{ github.event.number || github.ref_name }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  VOLTA_FEATURE_PNPM: 1

jobs:
  main:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout [Pull Request]
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: actions/checkout@v3
        name: Checkout [Default Branch]
        if: ${{ github.event_name != 'pull_request' }}
        with:
          fetch-depth: 0

      - name: Derive SHAs for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'main'

      - name: Setup volta
        uses: volta-cli/action@v4

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps

      - name: Initialize the Nx Cloud distributed CI run
        run: pnpm nx-cloud start-ci-run

      - name: Generate prisma client
        run: pnpm nx generate-client db

      - name: Build & Build storybook
        run: pnpm nx run-many -t build,build-storybook --parallel=3

      - name: Lint, Typecheck & Test
        run: pnpm nx run-many -t lint,typecheck,test:coverage --parallel=3

      - name: E2E
        run: pnpm nx run-many -t e2e --parallel=3

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
